<?php

/**
 * @file
 * Field Group extras
 * Horizontal tabs, multipage, accordions.
 */

require_once dirname(__FILE__) . '/field_group_extra.groups.inc';

/**
 * Implements hook_theme().
 */
function field_group_extra_theme() {
  return array(
    'horizontal_tabs' => array(
      'render element' => 'element',
      'file' => 'field_group_extra.theme.inc',
    ),
    'multipage' => array(
      'render element' => 'element',
      'file' => 'field_group_extra.theme.inc',
    ),
    'multipage_pane' => array(
      'render element' => 'element',
      'file' => 'field_group_extra.theme.inc',
    ),
  );
}

/**
 * Implements hook_element_info().
 */
function field_group_extra_element_info() {
  $types['horizontal_tabs'] = array(
    '#theme_wrappers' => array('horizontal_tabs'),
    '#default_tab' => '',
    '#process' => array('form_process_horizontal_tabs'),
  );
  $types['multipage'] = array(
    '#theme_wrappers' => array('multipage'),
    '#default_tab' => '',
    '#process' => array('form_process_multipage'),
  );
  $types['multipage_pane'] = array(
    '#value' => NULL,
    '#process' => array('form_process_fieldset', 'ajax_process_form'),
    '#pre_render' => array('form_pre_render_fieldset'),
    '#theme_wrappers' => array('multipage_pane'),
  );
  return $types;
}

/**
 * Implements hook_library_info().
 */
function field_group_extra_library_info() {
  $path = backdrop_get_path('module', 'field_group_extra');
  // Horizontal Tabs.
  $libraries['horizontal-tabs'] = array(
    'title' => 'Horizontal Tabs',
    'website' => 'http://drupal.org/node/323112',
    'version' => '1.0',
    'js' => array(
      $path . '/js/horizontal-tabs/horizontal-tabs.js' => array(),
    ),
    'css' => array(
      $path . '/css/horizontal-tabs/horizontal-tabs.css' => array(),
    ),
  );
  // Multipage Tabs.
  $libraries['multipage'] = array(
    'title' => 'Multipage',
    'website' => 'http://drupal.org/node/323112',
    'version' => '1.0',
    'js' => array(
      $path . '/js/multipage/multipage.js' => array(),
    ),
    'css' => array(
      $path . '/css/multipage/multipage.css' => array(),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_field_group_formatter_info().
 */
function field_group_extra_field_group_formatter_info() {
  return array(
    'form' => array(
      'htabs' => array(
        'label' => t('Horizontal tabs group'),
        'description' => t('This fieldgroup renders child groups in its own horizontal tabs wrapper.'),
        'instance_settings' => array('classes' => '', 'id' => ''),
      ),
      'htab' => array(
        'label' => t('Horizontal tab'),
        'format_types' => array('open', 'closed'),
        'description' => t('This fieldgroup renders the content in a fieldset, part of horizontal tabs group.'),
        'default_formatter' => 'closed',
        'instance_settings' => array('description' => '', 'classes' => '', 'required_fields' => 1),
      ),
      'multipage-group' => array(
        'label' => t('Multipage group'),
        'description' => t('This fieldgroup renders groups on separate pages.'),
        'instance_settings' => array('classes' => '', 'page_header' => 3, 'move_additional' => 1, 'page_counter' => 1, 'move_button' => 0),
      ),
      'multipage' => array(
        'label' => t('Multipage'),
        'format_types' => array('start', 'no-start'),
        'description' => t('This fieldgroup renders the content in a page.'),
        'default_formatter' => 'no-start',
        'instance_settings' => array('description' => '', 'classes' => '', 'required_fields' => 1),
      ),
      'accordion' => array(
        'label' => t('Accordion group'),
        'description' => t('This fieldgroup renders child groups as jQuery accordion.'),
        'instance_settings' => array('effect' => 'none', 'classes' => '', 'id' => ''),
      ),
      'accordion-item' => array(
        'label' => t('Accordion item'),
        'format_types' => array('open', 'closed'),
        'description' => t('This fieldgroup renders the content in a div, part of accordion group.'),
        'default_formatter' => 'closed',
        'instance_settings' => array('description' => '', 'classes' => '', 'required_fields' => 1),
      ),
    ),
    'display' => array(
      'htabs' => array(
        'label' => t('Horizontal tabs group'),
        'description' => t('This fieldgroup renders child groups in its own horizontal tabs wrapper.'),
        'instance_settings' => array('classes' => '', 'id' => ''),
      ),
      'htab' => array(
        'label' => t('Horizontal tab item'),
        'format_types' => array('open', 'closed'),
        'description' => t('This fieldgroup renders the content in a fieldset, part of horizontal tabs group.'),
        'instance_settings' => array('description' => '', 'classes' => '', 'id' => ''),
        'default_formatter' => 'closed',
      ),
      'accordion' => array(
        'label' => t('Accordion group'),
        'description' => t('This fieldgroup renders child groups as jQuery accordion.'),
        'instance_settings' => array('description' => '', 'classes' => '', 'effect' => 'bounceslide', 'id' => ''),
      ),
      'accordion-item' => array(
        'label' => t('Accordion item'),
        'format_types' => array('open', 'closed'),
        'description' => t('This fieldgroup renders the content in a div, part of accordion group.'),
        'instance_settings' => array('classes' => ''),
        'default_formatter' => 'closed',
      ),
    ),
  );
}

/**
 * Implements hook_field_group_format_settings_alter().
 */
function field_group_extra_field_group_format_settings_alter(&$form, &$group) {
  $field_group_types = field_group_formatter_info();
  $mode = $group->mode == 'form' ? 'form' : 'display';
  $formatter = $field_group_types[$mode][$group->format_type];

  // Add optional instance_settings.
  switch ($group->format_type) {
    case 'multipage-group':
      $form['instance_settings']['page_header'] = array(
        '#title' => t('Format page title'),
        '#type' => 'select',
        '#options' => array(0 => t('None'), 1 => t('Label only'), 2 => t('Step 1 of 10'), 3 => t('Step 1 of 10 [Label]'),),
        '#default_value' => isset($group->format_settings['instance_settings']['page_header']) ? $group->format_settings['instance_settings']['page_header'] : $formatter['instance_settings']['page_header'],
        '#weight' => 1,
      );
      $form['instance_settings']['page_counter'] = array(
        '#title' => t('Add a page counter at the bottom'),
        '#type' => 'select',
        '#options' => array(0 => t('No'), 1 => t('Format 1 / 10'), 2 => t('The count number only')),
        '#default_value' => isset($group->format_settings['instance_settings']['page_counter']) ? $group->format_settings['instance_settings']['page_counter'] : $formatter['instance_settings']['page_counter'],
        '#weight' => 2,
      );
      $form['instance_settings']['move_button'] = array(
        '#title' => t('Move submit button to last multipage'),
        '#type' => 'select',
        '#options' => array(0 => t('No'), 1 => t('Yes')),
        '#default_value' => isset($group->format_settings['instance_settings']['move_button']) ? $group->format_settings['instance_settings']['move_button'] : $formatter['instance_settings']['move_button'],
        '#weight' => 3,
      );
      $form['instance_settings']['move_additional'] = array(
        '#title' => t('Move additional settings to last multipage (if available)'),
        '#type' => 'select',
        '#options' => array(0 => t('No'), 1 => t('Yes')),
        '#default_value' => isset($group->format_settings['instance_settings']['move_additional']) ? $group->format_settings['instance_settings']['move_additional'] : $formatter['instance_settings']['move_additional'],
        '#weight' => 4,
      );
    case 'htabs':
      break;
    case 'accordion':
      $form['instance_settings']['effect'] = array(
        '#title' => t('Effect'),
        '#type' => 'select',
        '#options' => array('none' => t('None'), 'bounceslide' => t('Bounce slide')),
        '#default_value' => isset($group->format_settings['instance_settings']['effect']) ? $group->format_settings['instance_settings']['effect'] : $formatter['instance_settings']['effect'],
        '#weight' => 2,
      );
      break;
    case 'multipage':
      break;
    case 'htab':
    case 'accordion-item':
    default:
  }
}

/**
 * Implements hook_field_group_build_pre_render_alter().
 */
function field_group_extra_field_group_build_pre_render_alter(&$element) {
  $element['#attached']['js'][] = backdrop_get_path('module', 'field_group_extra') . '/js/field_groups.js';

  // Move additional settings to the last multipage pane if configured that way.
  // Note that multipages MUST be in the root of the form.
  foreach (element_children($element) as $name) {
    if (isset($element[$name]['#type']) && $element[$name]['#type'] == 'multipage' && isset($element['additional_settings'])) {
      $last_pane = NULL;
      foreach (element_children($element[$name], TRUE) as $pane) {
        $last_pane = $pane;
      }
      $element[$name][$last_pane]['additional_settings'] = $element['additional_settings'];
      unset($element['additional_settings']);
    }
  }
}

/**
 * Implements hook_field_group_field_ui_parent_requirements_alter().
 */
function field_group_extra_field_group_field_ui_parent_requirements_alter(&$parent_requirements, &$context) {
  $parent_requirements = array(
    'multipage' => array(
      'parent' => 'multipage-group',
      'message' => 'Each <em>Multipage</em> element needs to have a parent <em>Multipage group</em> element.',
    ),
    'htab' => array(
      'parent' => 'htabs',
      'message' => 'Each <em>Horizontal tab</em> element needs to have a parent <em>Horizontal tabs</em> group element.',
    ),
    'accordion-item' => array(
      'parent' => 'accordion',
      'message' => 'Each <em>Accordion item</em> element needs to have a parent <em>Accordion group</em> element.',
    ),
  );
}

/**
 * Implements hook_field_group_html_classes_alter().
 */
function field_group_extra_field_group_html_classes_alter(&$classes, &$group) {
  // Open or closed horizontal or vertical tabs will be collapsible by default.
  if ($group->format_type == 'htab') {
    $classes->required[] = 'collapsible';
  }

  if ($group->format_type == 'multipage') {
    $class_group_type = 'field-group-multipage';
    $classes->required[] = $class_group_type;
    if ((array_search($class_group_type, $classes->optional)) !== false) {
      unset($classes->optional[$class_group_type]);
    }
  }

  if (isset($group->format_settings['instance_settings'])) {
    // Extra required classes for accordions.
    if ($group->format_type == 'accordion') {
      $classes->required[] = 'field-group-' . $group->format_type . '-wrapper';
      $effect = isset($group->format_settings['instance_settings']['effect']) ? $group->format_settings['instance_settings']['effect'] : 'none';
      $classes->required[] = 'effect-' . $effect;
    }
  }
}

/**
 * Implements hook_field_group_mode_types_excluded_alter().
 *
 * @param array $excluded_types
 *   An array of excluded format types.
 * @param string $mode
 *   The mode: form or display.
 */
function field_group_extra_field_group_mode_types_excluded_alter(&$excluded_types, $mode) {
  if ($mode != 'form') {
    $excluded_types = array('multipage', 'multipage-group');
  }
}
